\set ON_ERROR_STOP on

-- Google Search Crawler schema (manual migration).
--
-- Default target schema is `finance_report_staging` to match the `fr-psql` environment.
-- Override it if needed:
--   fr-psql -v google_search_crawler_schema=public -f migrations/001_init.sql
\if :{?google_search_crawler_schema}
\else
\set google_search_crawler_schema finance_report_staging
\endif

BEGIN;

SET search_path TO :"google_search_crawler_schema", public;

CREATE OR REPLACE FUNCTION google_search_crawler_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS crawl_runs (
  seqno BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  run_id TEXT PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  request_json JSONB NOT NULL,
  item_count INTEGER NOT NULL,
  artifact_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS articles (
  seqno BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  article_id UUID PRIMARY KEY,
  fingerprint TEXT UNIQUE NOT NULL,
  canonical_url TEXT,
  title TEXT NOT NULL,
  summary TEXT,
  published_at DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS article_observations (
  seqno BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  observation_id UUID PRIMARY KEY,
  article_id UUID NOT NULL REFERENCES articles(article_id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  keyword TEXT NOT NULL,
  url TEXT,
  published_text TEXT,
  published_at_confidence TEXT NOT NULL,
  raw_payload JSONB NOT NULL,
  collected_at TIMESTAMPTZ NOT NULL,
  crawl_run_id TEXT REFERENCES crawl_runs(run_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (article_id, source, keyword, crawl_run_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS crawl_runs_seqno_key ON crawl_runs(seqno);
CREATE UNIQUE INDEX IF NOT EXISTS articles_seqno_key ON articles(seqno);
CREATE UNIQUE INDEX IF NOT EXISTS article_observations_seqno_key ON article_observations(seqno);

DROP TRIGGER IF EXISTS crawl_runs_set_updated_at ON crawl_runs;
CREATE TRIGGER crawl_runs_set_updated_at
BEFORE UPDATE ON crawl_runs
FOR EACH ROW
EXECUTE FUNCTION google_search_crawler_set_updated_at();

DROP TRIGGER IF EXISTS articles_set_updated_at ON articles;
CREATE TRIGGER articles_set_updated_at
BEFORE UPDATE ON articles
FOR EACH ROW
EXECUTE FUNCTION google_search_crawler_set_updated_at();

DROP TRIGGER IF EXISTS article_observations_set_updated_at ON article_observations;
CREATE TRIGGER article_observations_set_updated_at
BEFORE UPDATE ON article_observations
FOR EACH ROW
EXECUTE FUNCTION google_search_crawler_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_article_observations_keyword ON article_observations(keyword);
CREATE INDEX IF NOT EXISTS idx_articles_published_at ON articles(published_at);

COMMIT;
